name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: docker://crystax/android-ndk:latest # Ye container environment hai
        # Hum Buildozer ko directly docker container mein chalaenge
        continue-on-error: false
        env:
          SDKMAN_ACCEPT_LICENSE: "true"
        run: |
          apt-get update && apt-get install -y python3-pip git
          pip3 install --upgrade buildozer
          # Permission fix ke liye local path use kar rahe hain
          export BUILDOZER_HOME=.buildozer
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vijay_apk
          path: bin/*.apk
