name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer
      - name: Patch buildozer.spec
        run: |
          # Yeh command bina file khole usme changes kar degi
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          sed -i 's/#android.accept_sdk_license =/android.accept_sdk_license =/g' buildozer.spec
      - name: Build with Buildozer
        env:
          # Yeh environment variable SDK licenses ko automatically accept kar leta hai
          SDKMAN_ACCEPT_LICENSE: "true"
        run: |
          buildozer -v android debug
